### PR TITLE
Dev util

### PR DESCRIPTION
**Pull request by serhanif59**
de initial ajout de utilitaires bdd et controller sans contrôle de données formulaire

### CODE REVIEW

**Review by thenriet — COMMENTED** [review]
Ok for me, Ali explained to me what he did

**Comment by thenriet** [comment]
When cloned, you need to create a db.php with your credentials and change the last 2 lines as such : 
define('APP_DB_HOST', 'mysql:host=localhost');
define('APP_DB_NAME', 'bonheur_et_paillettes'); 

In the index.php file, after the $util->clearLog(); add the line : 
$util->testDatabase(); 

PS : Don't forget to composer install !

**Review by marcosigis — APPROVED** [review]
so far so good

**Review by thenriet — APPROVED** [review]
Ok for me, let's go

**Review by MehdiDAAJI — APPROVED** [review]
so sweet !!!

**Pull request merged**
